version: '3.7'
services:
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: "Ch4ng3m3!"
      POSTGRES_DB: awx

  rabbitmq:
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_VHOST: awx

  memcached:
    image: "memcached:alpine"

  awxweb:
    image: "ansible/awx_web:latest"
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    configs:
      - source: awx_credenciais
        target: /etc/tower/conf.d/credentials.py
      - source: awx_env
        target: /etc/tower/conf.d/environment.sh
      - source: awx_key
        target: /etc/tower/SECRET_KEY
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

  tasks:
    image: "ansible/awx_task:latest"
    depends_on:
      - awxweb
    hostname: awx
    user: root
    configs:
      - source: awx_credenciais
        target: /etc/tower/conf.d/credentials.py
      - source: awx_env
        target: /etc/tower/conf.d/environment.sh
      - source: awx_key
        target: /etc/tower/SECRET_KEY
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      
configs:
  awx_credenciais:
    file: ./credentials.py
  awx_env:
    file: ./environment.sh
  awx_key:
    file: SECRET_KEY
